port: 4730
httpPort: 8080
enableSSL: false
debugging: true
hostName: localhost
persistenceEngine:
  engine: postgres
  postgreSQL:
    host: localhost
    port: 5432
    dbName: gearman
    user: gearman
    password: gearman
    table: gearman_00
