port: 4730
httpPort: 8080
enableSSL: false
debugging: true
hostName: localhost
persistenceEngine:
  engine: dynamodb
  dynamoDB:
    endpoint: http://localhost:8000
    user: foo
    password: bar
    table: gearman3
