port: 4730
httpPort: 8080
enableSSL: false
debugging: true
hostName: localhost
jobQueuePersistenceEngine: hbase

zooKeeper:
  hosts:
  - localhost:2181

HBase:
  hosts:
  -  localhost
  port:
    2181



